# tools/reset-local-app-data.ps1
#
# One-off cleanup: wipes this machine's Electron userData directory for
# Fish Battle Arena (%APPDATA%\tiktok-fish-battle, named from package.json's
# "name" field, not the "Fish Battle Arena" productName used for branding).
# Both `npm run desktop` (dev) and the packaged .exe share this same folder
# by default, so residue from earlier dev-mode testing (an old
# localStorage-era session, a stale config/game.env from before the
# ADMIN_SECRET_KEY/AUTH_API_BASE_URL changes, etc.) can leak into a
# supposedly-fresh packaged-app run. This forces a genuinely clean first run.
#
# Safe to delete entirely: everything in this directory (cache, session
# storage, config/*.env, auth-token.bin) is either regenerated automatically
# on next launch or was itself generated by a previous run.

$ErrorActionPreference = 'Stop'

$appDataDir = Join-Path $env:APPDATA 'tiktok-fish-battle'

Write-Host "[reset] stopping any running Fish Battle Arena / electron.exe processes..."
Get-Process -Name 'Fish Battle Arena', 'electron' -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Seconds 1

if (Test-Path $appDataDir) {
    Write-Host "[reset] removing $appDataDir"
    Remove-Item -LiteralPath $appDataDir -Recurse -Force
    Write-Host "[reset] done - directory removed."
} else {
    Write-Host "[reset] $appDataDir does not exist - nothing to remove."
}
